### ISSUE TITLE
Configure nbviewer to include a link to the hub

### ISSUE THREAD

**Issue by rcthomas** [krinsman/clonenotebooks#3]
This may just be something nbviewer exposes as a configurable, or the option to expose the link to a hub that is running the nbviewer service.

**Comment by krinsman** [comment]
**1.** Well it would definitely be possible to include a custom frontpage which could probably have the link to the hub. 

**2.** Do you also want a link to the hub on _all_ of the NBViewer pages too (as long as NBViewer is being run by a hub)? That would also make sense.

**3.** Do you want both of the above options?

**4.** Do you want something else entirely instead and/or in addition to the above?

**Comment by rcthomas** [comment]
I choose (3).  I think if you just set it up to point to `base_url` of the service, which I think is / then it would work.

**Comment by krinsman** [comment]
OK I will start looking into this today. Hopefully it won't take too long.

**Comment by krinsman** [comment]
Ok this has been fixed by the latest commit. Make sure to look at the new line in the example `nbviewer_config.py`: https://github.com/krinsman/clonenotebooks/blob/master/Docker/nbviewer_config.py#L12

~~See the commit here: https://github.com/krinsman/clonenotebooks/commit/1d59b9e679727f80e9dcae5e2467bdaa657b2455~~
**EDIT:** Actually that commit did not do it, but the next one did: https://github.com/krinsman/clonenotebooks/commit/75b70fb15abcac220ede37d83246aee62ec46b21 **/EDIT**

The changes assume that NBViewer is served at `<hub_base_url>/services/nbviewer`, so that `../..` with respect to the NBViewer base URL is exactly what it needs to be (`<hub_base_url>`).
