### ISSUE TITLE
More nbviewer and JupyterLab integration

### ISSUE THREAD

**Issue by rcthomas** [krinsman/clonenotebooks#5]
For instance, nbviewer popping up a new JupyterLab workspace; can workspaces be targeted and  can a workspace pass along a redirect param that would send copied notebooks back to the origin workspace?

**Comment by krinsman** [comment]
Would it be possible to add more details about what you have in mind? 

Currently how it works is that, whatever tab the user is looking at NBViewer in, gets redirected to JupyterLab. If the user already has JupyterLab open in another tab, that automatically means two tabs open with JupyterLab in them. And JupyterLab automatically creates a second workspace if two tabs are open and running JupyterLab. 

So do you mean you would prefer that this extension somehow checks whether there is already a currently open JupyterLab tab? And if there is one, then have it do the cloning in some way that doesn't redirect to JupyterLab? (I guess then there would somehow be an informational alert saying "hey we didn't redirect you because you already have JupyterLab open -- go to your other tab where you have JupyterLab open and look for your new notebook there.)

**Comment by krinsman** [comment]
I was thinking of somehow using the [IFrame extension](https://github.com/timkpaine/jupyterlab_iframe) to run NBViewer in an IFrame by default, but even in that case I would have to be careful about how the redirect works, since I'm pretty sure that even if it is possible, we wouldn't want to run JupyterLab inside of an IFrame inside of a JupyterLab tab. So I guess either way it's necessary to confront the multiple workspaces issue somehow.

**Comment by rcthomas** [comment]
I think this is also hard to accomplish before there's some idea of how JupyterLab and JupyterHub services are supposed to interact.  If we come to understand that then maybe we can revisit.  I think this is a larger issue that needs to be solved at the Lab level...
